"""add contact_number to users table

Revision ID: bd5ca05b76fc
Revises: 3aa8da77dc4c
Create Date: 2024-04-11 12:57:46.079246

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd5ca05b76fc"
down_revision = "3aa8da77dc4c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("contact_number", sa.String(length=13), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("contact_number")

    # ### end Alembic commands ###
